version: "3.9"
services:
  app:
    build: .
    container_name: facerecserver
    command: gunicorn --timeout 240 --workers 1 --bind 0.0.0.0:8000 FaceRecognitionServer.wsgi
    volumes:
      - .:/FaceRecognitionServer:z
    ports:
      - 5555:5555
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: facerecserver_db
    command: postgres -c 'max_connections=2000'
    volumes:
      - ./data/db:/var/lib/postgresql/data:z
    environment:
      - POSTGRES_DB=facerecognitionserver
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
  nginx:
    build: ./nginx
    container_name: facerecserver_nginx
    depends_on:
      - app
    volumes:
      - ./static/:/var/www/static:z
      - ./media/:/var/www/media:z
    ports:
      - "80:80"
      - "443:443"
