version: "3.9"
services:
  app:
    build: .
    container_name: facerecserver
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/FaceRecognitionServer
    ports:
      - 8000:8000
      - 5555:5555
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: facerecserver_db
    command: postgres -c 'max_connections=2000'
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=facerecognitionserver
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
      
