# Generated by Django 4.1.2 on 2022-11-14 09:55

import FaceRecognition.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('stream', models.CharField(max_length=255)),
                ('entrance', models.BooleanField(default=False)),
                ('exit', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'persons',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('visited', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('ip', models.CharField(default='192.168.1.52', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Servers',
            },
        ),
        migrations.CreateModel(
            name='SSHProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('encrypted_password', FaceRecognition.models.PasswordField()),
            ],
            options={
                'verbose_name_plural': 'SSHProfiles',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('file', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'staff',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(verbose_name='Seen at')),
                ('camera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FaceRecognition.camera')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FaceRecognition.person')),
            ],
            options={
                'verbose_name_plural': 'logs',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=255)),
                ('ssh_access', models.BooleanField(default=True)),
                ('cameras', models.ManyToManyField(to='FaceRecognition.camera')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FaceRecognition.server')),
                ('ssh_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FaceRecognition.sshprofile')),
            ],
            options={
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.AddField(
            model_name='camera',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FaceRecognition.room'),
        ),
    ]
