# Generated by Django 4.1.2 on 2022-10-10 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('stream', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_in_dsc', models.CharField(max_length=10, verbose_name='ID in the list of descriptors')),
            ],
            options={
                'verbose_name_plural': 'persons',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('visited', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('file', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'staff',
            },
        ),
        migrations.CreateModel(
            name='Unipi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=255)),
                ('username', models.CharField(default='pi', max_length=255)),
                ('password', models.CharField(default='raspberry', max_length=255)),
                ('server_ip', models.CharField(max_length=255)),
                ('camera1', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camera1', to='FaceRecognition.camera')),
                ('camera2', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camera2', to='FaceRecognition.camera')),
            ],
            options={
                'verbose_name_plural': 'Unipis',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(verbose_name='Seen at')),
                ('camera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FaceRecognition.camera')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FaceRecognition.person')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FaceRecognition.room')),
            ],
            options={
                'verbose_name_plural': 'logs',
            },
        ),
        migrations.AddField(
            model_name='camera',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FaceRecognition.room'),
        ),
    ]
