# Generated by Django 4.1.2 on 2022-10-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecognition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='visited',
            field=models.IntegerField(default=0),
        ),
    ]
