# Generated by Django 4.1.2 on 2022-10-10 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecognition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unipi',
            name='camera1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='camera1', to='FaceRecognition.camera'),
            preserve_default=False,
        ),
    ]
