# Generated by Django 4.1.2 on 2022-10-20 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecognition', '0003_alter_person_id_in_dsc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='id_in_dsc',
        ),
    ]
