# Generated by Django 4.1.2 on 2022-10-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecognition', '0004_remove_person_id_in_dsc'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='entrance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='camera',
            name='exit',
            field=models.BooleanField(default=False),
        ),
    ]
