# Generated by Django 4.1.2 on 2022-10-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecognition', '0005_camera_entrance_camera_exit'),
    ]

    operations = [
        migrations.AddField(
            model_name='unipi',
            name='push',
            field=models.BooleanField(default=True),
        ),
    ]
