# Generated by Django 4.1.2 on 2022-10-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecognition', '0006_unipi_push'),
    ]

    operations = [
        migrations.AddField(
            model_name='unipi',
            name='restart',
            field=models.BooleanField(default=True),
        ),
    ]
