# Generated by Django 4.1.2 on 2022-10-21 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecognition', '0007_unipi_restart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unipi',
            old_name='push',
            new_name='ssh',
        ),
        migrations.RemoveField(
            model_name='unipi',
            name='restart',
        ),
    ]
