# Generated by Django 4.1.2 on 2022-10-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecognition', '0008_rename_push_unipi_ssh_remove_unipi_restart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unipi',
            name='server_ip',
            field=models.CharField(default='192.168.1.52', max_length=255),
        ),
    ]
