# Generated by Django 4.1.2 on 2022-11-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecognition', '0010_rename_unipi_client_alter_client_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='room',
        ),
        migrations.AlterField(
            model_name='client',
            name='server_ip',
            field=models.CharField(default='192.168.1.22', max_length=255),
        ),
    ]
