# Generated by Django 4.1.3 on 2022-11-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecognition', '0011_remove_log_room_alter_client_server_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='server_ip',
            field=models.CharField(default='192.168.1.52', max_length=255),
        ),
    ]
