# Generated by Django 4.1.2 on 2022-11-12 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecognition', '0013_server_sshprofile_rename_ssh_client_ssh_access_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={'verbose_name_plural': 'Servers'},
        ),
        migrations.AddField(
            model_name='client',
            name='cameras',
            field=models.ManyToManyField(to='FaceRecognition.camera'),
        ),
        migrations.AlterField(
            model_name='client',
            name='server',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='FaceRecognition.server'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='ssh_profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='FaceRecognition.sshprofile'),
            preserve_default=False,
        ),
    ]
