# Generated by Django 4.1.2 on 2022-11-12 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecognition', '0014_alter_server_options_client_cameras_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='camera1',
        ),
        migrations.RemoveField(
            model_name='client',
            name='camera2',
        ),
    ]
