# Generated by Django 4.1.3 on 2022-11-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecognition', '0015_remove_client_camera1_remove_client_camera2'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='port',
            field=models.IntegerField(default=5555),
        ),
    ]
