# Generated by Django 4.1.3 on 2022-11-12 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecognition', '0016_server_port'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='port',
        ),
    ]
