# Generated by Django 4.1.2 on 2022-11-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecognition', '0017_remove_server_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sshprofile',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sshprofile',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
